Repository trailofbits/polytracker, pull requests merged in 2021-04, with the labels that each got.

#6359 Fix various database bugs and update to the latest polytracker-llvm
  Dockerfile
  polytracker/cache.py
  polytracker/database.py
  polytracker/include/polytracker/output.h
  polytracker/inputs.py
  polytracker/src/passes/polytracker_pass.cpp
  polytracker/src/polytracker/logging.cpp
  polytracker/src/polytracker/output.cpp
  polytracker/taint_forest.py
  polytracker/tracing.py
  tests/test_cache.py
  tests/test_polytracker.py
Labels: bug

#6360 Various database schema and access API changes for a speedup
  README.md
  examples/Dockerfile-jq.demo
  polytracker/database.py
  polytracker/grammars.py
  polytracker/include/polytracker/logging.h
  polytracker/include/polytracker/output.h
  polytracker/include/polytracker/polytracker.h
  polytracker/src/polytracker/logging.cpp
  polytracker/src/polytracker/output.cpp
  polytracker/src/polytracker/tablegen.cpp
  polytracker/src/polytracker/taint.cpp
  polytracker/tracing.py
  tests/conftest.py
  tests/data.py
  tests/test_bb_splitting.c
  tests/test_bb_splitting.py
  tests/test_data/.dockerignore
  tests/test_data/.gitignore
  tests/test_grammars.py
  tests/test_polytracker.py
  tests/tracing.py
Labels: enhancement

#6362 Adds auto-generated documentation with Sphinx
  .dockerignore
  .github/workflows/publish_docs.yml
  README.md
  docs/.gitignore
  docs/Makefile
  docs/_static/localtoc.js
  docs/_templates/layout.html
  docs/_templates/searchbox.html
  docs/build_api.py
  docs/conf.py
  docs/index.rst
  docs/makefuncs.py
  polytracker/__init__.py
  polytracker/inputs.py
  polytracker/plugins.py
  polytracker/polytracker.py
  polytracker/tracing.py
  setup.py
Labels: developer-friendliness, documentation, enhancement

#6373 Remove references from logging which prevent TCO
  polytracker/include/polytracker/logging.h
  polytracker/src/polytracker/logging.cpp
Labels: enhancement

#6374 If no polypath is specified, always taint
  polytracker/src/polytracker/main.cpp
  polytracker/src/polytracker/taint.cpp
Labels: enhancement
